### ISSUE TITLE
wrong multi-disc albums tracks tagging

### ISSUE THREAD

**Issue by Victorbry99** [HOZHENWAI/Beets-Plugin_VGMdb#16]
I set ``` per_disc_numbering: yes ``` and it works good with musicbrainz, but not with vgmdb plugin. all the tracks numbers are shifted -1, because it starts counting from 0, i.e. 00 01 02 03 ... . Also discs get tagged starting from 0, so for example a 2-discs album is tagged as Disc 0 and Disc 1, instead of Disc 1 and Disc 2.

here is an example multi-disc album, which is tagged correctly using musicbrainz using the same config:
https://vgmdb.net/album/27021
https://musicbrainz.org/release/3cf7f8ef-239f-47db-8537-3882ce65a750

**Comment by HOZHENWAI** [comment]
ok, i changed the numbering to start from 1,

**Comment by Victorbry99** [comment]
works good, thanks
