### ISSUE TITLE
ModuleNotFound?

### ISSUE THREAD

**Issue by blitzmikyu** [HOZHENWAI/Beets-Plugin_VGMdb#21]
Not sure what I've done wrong. It says its successfully installed.

root@09d35f867f82:/config# beet version
** error loading plugin vgmdb:
Traceback (most recent call last):
  File "/lsiopy/lib/python3.11/site-packages/beets/plugins.py", line 268, in load_plugins
    namespace = __import__(modname, None, None)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'beetsplug.vgmdb'

**Comment by HOZHENWAI** [comment]
what is your config like?

**Comment by HOZHENWAI** [comment]
ok, I should update the readme.
There are two plugins actually, I think you put
`plugins: vgmdb`
in the config.
There are two plugins:
`VGMplug`
which is the metadata fetcher and distance computer
and 
`VGMCollection`
which deals with your collection on vgmdb, to auto add and remove the album on the website on your account

**Comment by blitzmikyu** [comment]
Thank you, yes that was my issue. I put in vgmdb under plugins.

Seems to be a issue querying now though. I put in the ID for https://vgmdb.net/album/55565. (55565)
Its saying there is a network problem. Do I need both plugins and do I also need a vgmdb account just to scrape?

Enter search, enter Id, aBort, type Vgmdb id, type vgmdb Query? v
Enter release ID: 55565
VGMplug: Network Problem: 55565
VGMplug: Asking a manual id that has issues. 55565

**Comment by HOZHENWAI** [comment]
Ok, thank you for telling me this. I will explain the issue:
- i'm actually using the `vgmdb.info` api which is a public api that someone made to access easily the information on vgmdb since the site has no official api (at least when I created the plugin), so `vgmdb.info` is different from `vgmdb.net`
- i already have tickets for build myself a parser for vgmdb.net (#10 ) but I kinda put this on hold since `vgmdb.info` did the job when I created the plugin.
- unfortunately it seems the `vgmdb.info` website is down (at least the album api); for example: go to `http://vgmdb.info/albumlist`, click on any album, you will have an error.
Therefore, this weekend, I will try to work on #10 to solve the issue. Right now, the plugin doesn't work unless the issue with vgmdb.info is fixed.

**Comment by blitzmikyu** [comment]
I just tried it again, seems to work now. I guess it was due to the outage. Its good to know that it uses vgmdb.info as the source. Thank you for clarifying that for me. Thank you for the excellent work!

# selection (default 1), Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort, type Vgmdb id, type vgmdb Query? v
Enter release ID: 55565
VGMplug: Completing artist info using composers
VGMplug: Completing artist info using performers
VGMplug: Found 16 performers
VGMplug: Final artist choice is Mai Nakahara
Correcting tags from:
    Various Artists - Drama CD CLANNAD - Hikari Mimamoru Sakamichi de Vol. 1
To:
    Mai Nakahara - Drama CD CLANNAD Hikari Mimamoru Sakamichi de Vol.1
URL:
    https://vgmdb.net/album/55565?perpage=99999
(Similarity: 68.9%) (tracks, artist) (VGMdb, 2x2 CD, 2007, 株式会社プロトタイプ, PROT-001)
2 CD 1: Disc 1
 * Dai 1 Wa Yuuki wo Dashite －Furukawa Nagisa－ ->
   第１話 勇気を出して (title)
 * Dai 2 Wa Kouko no Nikki －Ibuki Kouko－ ->
   第２話 公子の日記 (title)
2 CD 2: Disc 2
 * Dai 3 Wa Otokotomodachi －Fujibayashi Kyou－ (#1) ->
   第３話 男友達 (#3) (title)
 * Dai 4 Wa Tokimeku Shunkan －Fujibayashi Ryou－ (#2) ->
   第４話 ときめく瞬間 (#4) (title)
Apply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort, type Vgmdb id, type vgmdb Query?

**Comment by blitzmikyu** [comment]
It looks like I need to hit http://vgmdb.info/album/??????  manually and then it'll pull the data from .net. That is fine.

**Comment by HOZHENWAI** [comment]
If you have any feature request with the usage of the plugin let me know. Btw, you don't have to hit on "vgmdb.info", the album id are the same on both. If you search for an album on vgmdb.net, you can use the same id, you can also search directly using the Q option.
