### ISSUE TITLE
Assign album type by default

### ISSUE THREAD

**Issue by ivan-boikov** [HOZHENWAI/Beets-Plugin_VGMdb#23]
MusicBrainz assigns a `soundtrack` album type where applicable. Mediainfo then shows:
```shell
RELEASETYPE                              : album / soundtrack
MUSICBRAINZ_ALBUMTYPE                    : album / soundtrack
```
This allows `albumtype` plugin to sort soundtracks to a soundtrack directory.

Seeing as VGMdb is for OSTs, can the plugin assign this album type by default?

In my library all OSTs are `album / soundtrack`, don't know if it's like that everywhere.

**Comment by HOZHENWAI** [comment]
This is a sensible default, will update the plugin.

**Comment by HOZHENWAI** [comment]
Actually, after looking at some album on vgmdb, there are album that are not soundtracks... You can find anime single, albums and even audio drama... We need more information to determine the album type... I believe the game category are more likely to hold soundtrack but it is not uncommon for anime to also have soundtracks... We could either make a prediction and then ask the user for confirmation

**Comment by HOZHENWAI** [comment]
we could even create a session default albumtype for import to reduce user interaction (for album import using this plugin), will think about it before proposing a solution

**Comment by ivan-boikov** [comment]
Yes, you are right, I totally overlooked such entries! Feel free to close the issue if you prefer.

**Comment by HOZHENWAI** [comment]
there is classification field for the album... just need to match. Will close in favor of #24

**Comment by HOZHENWAI** [comment]
@ivan-boikov just so you know, a new version has been pushed with the album type... see the readme to update your `albumtype` config
